export const SET_CONTACTS_LIST = 'SET_CONTACTS_LIST';
export const SET_DUPLICATE_CONTACT_LIST = 'SET_DUPLICATE_CONTACT_LIST';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_LOADING = 'SET_LOADING';
